FROM registry.access.redhat.com/ubi9/ubi-micro:latest AS staging
COPY plugins/ecs/backend/dist-dynamic  /staging/aws-amazon-ecs-plugin-for-backstage-backend/
COPY plugins/ecs/frontend/dist-dynamic /staging/aws-amazon-ecs-plugin-for-backstage-frontend/
COPY plugins/ecr/backend/dist-dynamic  /staging/aws-amazon-ecr-plugin-for-backstage-backend/
COPY plugins/ecr/frontend/dist-dynamic /staging/aws-amazon-ecr-plugin-for-backstage-frontend/
COPY plugins/cost-insights/backend/dist-dynamic  /staging/aws-cost-insights-plugin-for-backstage-backend/
COPY plugins/cost-insights/frontend/dist-dynamic /staging/aws-cost-insights-plugin-for-backstage-frontend/
COPY plugins/securityhub/backend/dist-dynamic  /staging/aws-securityhub-plugin-for-backstage-backend/
COPY plugins/securityhub/frontend/dist-dynamic /staging/aws-securityhub-plugin-for-backstage-frontend/
COPY plugins/genai/backend/dist-dynamic         /staging/aws-genai-plugin-for-backstage-backend/
COPY plugins/genai/frontend/dist-dynamic        /staging/aws-genai-plugin-for-backstage-frontend/
COPY plugins/genai/agent-langgraph/dist-dynamic /staging/aws-genai-plugin-langgraph-agent-for-backstage/

FROM scratch
COPY --from=staging /staging/ /
