services:
  devportal:
    image: veecode/devportal:latest
    ports:
      - "7007:7007"
    environment:
      - DEVELOPMENT=true
      - LOG_LEVEL=info
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_REGION=us-east-1
    volumes:
      - ./app-config.dynamic.yaml:/app/app-config.local.yaml:ro
      - ./dynamic-plugins.yaml:/app/dynamic-plugins.yaml:ro
      # examples
      - ./examples:/app/examples:ro
      # mounting dist-dynamic directly, no need to npm publish
      - ./plugins/ecs/backend/dist-dynamic:/app/dynamic-plugins/dist/aws-amazon-ecs-plugin-for-backstage-backend-dynamic:ro
      - ./plugins/ecs/frontend/dist-dynamic:/app/dynamic-plugins/dist/aws-amazon-ecs-plugin-for-backstage-dynamic:ro
      - ./plugins/ecr/backend/dist-dynamic:/app/dynamic-plugins/dist/aws-amazon-ecr-plugin-for-backstage-backend-dynamic:ro
      - ./plugins/ecr/frontend/dist-dynamic:/app/dynamic-plugins/dist/aws-amazon-ecr-plugin-for-backstage-dynamic:ro
      - ./plugins/cost-insights/backend/dist-dynamic:/app/dynamic-plugins/dist/aws-cost-insights-plugin-for-backstage-backend-dynamic:ro
      - ./plugins/cost-insights/frontend/dist-dynamic:/app/dynamic-plugins/dist/aws-cost-insights-plugin-for-backstage-dynamic:ro
